{
 "title": "dashboard",
 "time": { "from": "2025-04-29T21:27:04.408Z", "to": "2025-04-30T09:27:04.408Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Disc I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance)(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}} CPU usage"
    }
   ]
  },
  {
   "title": "Request in Last hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (job) (increase(promhttp_metric_handler_requests_total[1h]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)",
     "legendFormat": "Memory % used"
    }
   ]
  },
  {
   "title": "Total Inference Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "inference_requests_total" }
   ]
  },
  {
   "title": "Failed Predictions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "failed_predictions_total" }
   ]
  },
  {
   "title": "Successful Predictions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "successful_predictions_total" }
   ]
  },
  {
   "title": "Total Feedback Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "feedbacks_total" }
   ]
  },
  {
   "title": " HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (job)(\r\n  rate(promhttp_metric_handler_requests_total[1m])\r\n)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}