preprocess:
  image_size: 120
  
split:
  seed: 42
  train: 0.8 
  val: 0.1
  test: 0.1

dataloader:
  image_size: 120
  train_batch_size: 32
  val_batch_size: 32
  num_workers: 4
  
train:
  epochs: 1
  lr: 0.001

evaluate:
  test_batch_size: 32
